### ISSUE TITLE
[Bug]: KeyError: 'settings'

### ISSUE THREAD

**Issue by josephzsombor** [Anselmoo/spectrafit#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the input files from the example section of the documentation, SpectraFit crashes with the following error:
Traceback (most recent call last):
  File "/$HOME/.local/bin/spectrafit", line 8, in <module>
    sys.exit(command_line_runner())
  File "/$HOME/.local/pipx/venvs/spectrafit/lib/python3.7/site-packages/spectrafit/spectrafit.py", line 192, in command_line_runner
    args = extracted_from_command_line_runner()
  File "/$HOME/.local/pipx/venvs/spectrafit/lib/python3.7/site-packages/spectrafit/spectrafit.py", line 230, in extracted_from_command_line_runner
    check_keywords_consistency(check_args=_args["settings"], ref_args=result)
KeyError: 'settings'

Adding ' "settings":{}, ' to the beginning of example.json solves the issue

### Steps To Reproduce

spectrafit data.txt -i example.json

### ⚙️ Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.7.5
- spectrafit:0.8.6
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anselmoo** [comment]
@josephzsombor thx
